name: school_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  #* State management
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  hydrated_bloc: ^10.0.0

  #* Data class
  freezed_annotation: ^2.4.4
  fpdart: ^1.1.1
  json_annotation: ^4.9.0

  #* Path
  path_provider: ^2.1.5

  #* UI
  meta: ^1.15.0
  morphable_shape: ^2.0.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1

  #* Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  get_it: ^8.2.0

  #* Database
  sqflite: ^2.4.2

dependency_overrides:
  meta: ^1.15.0

dev_dependencies:
  #* Test
  flutter_test:
    sdk: flutter

  #* Data Class
  freezed: ^2.5.8
  build_runner: ^2.4.14
  json_serializable: ^6.9.4

  #* for analyse packages
  very_good_analysis: ^6.0.0

  #* for save image
  file_saver: ^0.2.14

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/svg/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
